// SCREENS
export const SCREEN_TEST = 'SCREEN_TEST';

export const SCREEN_SPLASH = 'SCREEN_SPLASH';
export const SCREEN_MAIN = 'SCREEN_MAIN';
export const SCREEN_RESULTS = 'SCREEN_RESULTS';
export const SCREEN_IMAGE = 'SCREEN_IMAGE';
export const SCREEN_CHECKOUT = 'SCREEN_CHECKOUT';
